### ISSUE TITLE
Update on a Raspberry Pi 4

### ISSUE THREAD

**Issue by rgrosser71** [YunoHost-Apps/uptime-kuma_ynh#69]
Hi,

i can not update to current Version.

I've running a 
-Raspberry Pi 4 4GB
-YunoHost version: 11.1.21.4
- I have access to my server: through the webadmin/CLI
- Using, or trying to install package version/branch:  1.20.2~ynh1 to1.21.3~ynh1

### Steps to reproduce
webadmin: "This app can only be installed on certain amd64 architectures, but your current server architecture is arm64"
Putty: root@yunohost:~# yunohost app upgrade uptime-kuma
          Info: Now upgrading uptime-kuma...
          Error: This app can only be installed on architectures amd64 but your server architecture is arm64

**Comment by ketsapiwiq** [comment]
Hi @rgrosser71 !

I couldn't test on Raspberry so I specified it couldn't be installed there, but it's probably dumb because it should be possible.

Can you try the following command to test if just removing the AMD64 architecture constraint makes it just work?
`sudo yunohost app upgrade uptime-kuma -u https://github.com/YunoHost-Apps/uptime-kuma_ynh/tree/testing -F`

Ping @rmdes if you're interested to try :)

Many thanks!

**Comment by rmdes** [comment]
Will try today, I know it used to work some time ago! Thanks!

**Comment by ketsapiwiq** [comment]
Thank you!
